# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy to heroku

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - run: pwd
      - run: ls
      - uses: actions/checkout@master
        with:
          repository: mildshower/super-card-react
          path: another
      - run: pwd
      - run: ls
